// Generated by CoffeeScript 1.6.3
(function() {
  var meeting, query, sysRecords;

  sysRecords = require('../db/sys').data;

  meeting = require('./meeting');

  exports.list = function(req, res) {
    return res.send("respond with a resource");
  };

  exports.getByEmployeeId = function(req, res) {
    res.setHeader('content-type', 'text/json;charset=UTF-8');
    return res.json(200, query('EmployeeId', req.params.employeeId));
  };

  exports.get_dper_today_meetings = function(req, res) {
    var meetings, result;
    result = {
      code: 200,
      msg: null
    };
    meetings = meeting.queryDper("Name", req.params.name).msg;
    console.log(meetings);
    result.msg = meetings.map(function(item) {
      var room;
      return room = {
        Name: req.params.name,
        MeetingRoom: item.MeetingRoom,
        STime: item.STime,
        ETime: item.ETime
      };
    });
    res.setHeader('content-type', 'text/json;charset=UTF-8');
    return res.json(200, result);
  };

  query = function(key, val) {
    var result;
    result = {
      code: 500,
      msg: null
    };
    result.msg = sysRecords.filter(function(item) {
      return item.loginId.indexOf(val) !== -1;
    });
    if (result.msg.length > 0) {
      result.code = 200;
    }
    return result;
  };

}).call(this);
