// Generated by CoffeeScript 1.6.3
(function() {
  var query, sysRecords;

  sysRecords = require('../db/sys').data;

  exports.list = function(req, res) {
    return res.send("respond with a resource");
  };

  exports.getByEmployeeId = function(req, res) {
    res.setHeader('content-type', 'text/json;charset=UTF-8');
    return res.json(200, query('EmployeeId', req.params.employeeId));
  };

  query = function(key, val) {
    var result;
    result = {
      code: 500,
      msg: null
    };
    result.msg = sysRecords.filter(function(item) {
      return item.loginId.indexOf(val) !== -1;
    });
    if (result.msg.length > 0) {
      result.code = 200;
    }
    return result;
  };

}).call(this);
