// Generated by CoffeeScript 1.6.3
(function() {
  var query, sysRecords;

  sysRecords = require('../db/sys').data;

  exports.list = function(req, res) {
    return res.send("respond with a resource");
  };

  exports.getByEmployeeId = function(req, res) {
    res.setHeader('content-type', 'text/json;charset=UTF-8');
    return res.json(200, query('EmployeeId', req.params.employeeId));
  };

  query = exports.query = function(key, val) {
    return sysRecords.filter(function(item) {
      return item[key].indexOf(val) !== -1;
    });
  };

}).call(this);
