// Generated by CoffeeScript 1.6.3
(function() {
  var meetingRecords, query, queryCurrentMeetingRoom;

  meetingRecords = require('../db/meeting').data;

  exports.getByEmail = function(req, res) {
    res.setHeader('content-type', 'text/json;charset=UTF-8');
    res.json(200, query('Email', req.params.email));
  };

  exports.getByDper = function(req, res) {
    res.setHeader('content-type', 'text/json;charset=UTF-8');
    return res.json(200, query('Name', req.params.dper));
  };

  exports.get_deper_current_room = function(req, res) {
    var current_room, current_time, result, room_list;
    room_list = query('Name', req.params.dper);
    current_time = +(new Date);
    current_room = room_list.filter(function(room) {
      var end_time, start_time;
      start_time = +new Date("2013-" + room.STime);
      end_time = +new Date("2013-" + room.ETime);
      return current_time >= start_time && current_time <= end_time;
    });
    result = current_room.length === 0 ? "他／她暂时不在开会，难道就在座位上？！" : current_room;
    res.setHeader('content-type', 'text/json;charset=UTF-8');
    return res.json(200, result);
  };

  query = exports.query = function(key, val) {
    return meetingRecords.filter(function(item) {
      var dpers;
      dpers = item.Attendees.filter(function(dper) {
        if (dper.Name !== null) {
          return dper[key].indexOf(val) !== -1;
        }
      });
      return dpers.length > 0;
    });
  };

  queryCurrentMeetingRoom = exports.queryCurrentMeetingRoom = function(email) {
    var currentDate, currentRoom, currentRooms, result, roomList;
    roomList = query('Email', email);
    currentDate = new Date();
    currentRooms = roomList.filter(function(room) {
      var currentTime, endTime, startTime;
      startTime = +new Date(currentDate.getFullYear() + '-' + room.STime);
      endTime = +new Date(currentDate.getFullYear() + '-' + room.ETime);
      currentTime = currentDate.getTime() - 24 * 60 * 60 * 1000;
      return currentTime >= startTime && currentTime <= endTime;
    });
    currentRoom = currentRooms.sort(function(a, b) {
      var aStartTime, bStartTime;
      aStartTime = +new Date(currentDate.getFullYear() + '-' + a.STime);
      bStartTime = +new Date(currentDate.getFullYear() + '-' + b.STime);
      return aStartTime - bStartTime > 0;
    });
    return result = currentRoom.length ? currentRoom[0] : null;
  };

}).call(this);
